"""create Booking model

Revision ID: 1cbb2156ecbc
Revises: db39286b4810
Create Date: 2026-09-16 16:13:55.241163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbb2156ecbc'
down_revision: Union[str, Sequence[str], None] = 'db39286b4810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rider_id', sa.UUID(), nullable=False),
    sa.Column('pickup_stop_id', sa.UUID(), nullable=False),
    sa.Column('dropoff_stop_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('seats_booked', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'expired', name='booking_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dropoff_stop_id'], ['route_stops.id'], ),
    sa.ForeignKeyConstraint(['pickup_stop_id'], ['route_stops.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_dropoff_stop_id'), 'bookings', ['dropoff_stop_id'], unique=False)
    op.create_index(op.f('ix_bookings_pickup_stop_id'), 'bookings', ['pickup_stop_id'], unique=False)
    op.create_index(op.f('ix_bookings_rider_id'), 'bookings', ['rider_id'], unique=False)
    op.create_index(op.f('ix_bookings_trip_id'), 'bookings', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_trip_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_rider_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_pickup_stop_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_dropoff_stop_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
