"""Add notification type

Revision ID: 5a970c10d80e
Revises: e9acfb472a00
Create Date: 2026-09-22 14:18:45.399773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a970c10d80e'
down_revision: Union[str, Sequence[str], None] = 'e9acfb472a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE notification_type ADD VALUE 'trip_created'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
