"""create-ride-preference

Revision ID: 791e1875813a
Revises: 1cbb2156ecbc
Create Date: 2026-09-21 22:30:22.428213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791e1875813a'
down_revision: Union[str, Sequence[str], None] = '1cbb2156ecbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rider_id', sa.UUID(), nullable=False),
    sa.Column('source_location_id', sa.UUID(), nullable=False),
    sa.Column('destination_location_id', sa.UUID(), nullable=False),
    sa.Column('preferred_departure_time', sa.Time(), nullable=True),
    sa.Column('seats_needed', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_location_id != destination_location_id', name='check_ride_pref_different_locations'),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_preferences_destination_location_id'), 'ride_preferences', ['destination_location_id'], unique=False)
    op.create_index(op.f('ix_ride_preferences_rider_id'), 'ride_preferences', ['rider_id'], unique=False)
    op.create_index(op.f('ix_ride_preferences_source_location_id'), 'ride_preferences', ['source_location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ride_preferences_source_location_id'), table_name='ride_preferences')
    op.drop_index(op.f('ix_ride_preferences_rider_id'), table_name='ride_preferences')
    op.drop_index(op.f('ix_ride_preferences_destination_location_id'), table_name='ride_preferences')
    op.drop_table('ride_preferences')
    # ### end Alembic commands ###
