"""Create route tables

Revision ID: 8555a33fc6cc
Revises: 8912871ce754
Create Date: 2026-09-11 09:44:42.740228

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8555a33fc6cc"
down_revision: Union[str, Sequence[str], None] = "8912871ce754"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_routes_driver_id"), "routes", ["driver_id"], unique=False)
    op.create_table(
        "route_stops",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_route_stops_location_id"), "route_stops", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_route_stops_route_id"), "route_stops", ["route_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_route_stops_route_id"), table_name="route_stops")
    op.drop_index(op.f("ix_route_stops_location_id"), table_name="route_stops")
    op.drop_table("route_stops")
    op.drop_index(op.f("ix_routes_driver_id"), table_name="routes")
    op.drop_table("routes")
    # ### end Alembic commands ###
