"""create the Booking model

Revision ID: c444a5db0c2f
Revises: 627e83e3fd6b
Create Date: 2026-09-07 11:41:20.111215

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c444a5db0c2f"
down_revision: Union[str, Sequence[str], None] = "627e83e3fd6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("rider_id", sa.UUID(), nullable=False),
        sa.Column("pickup_stop_id", sa.UUID(), nullable=False),
        sa.Column("dropoff_stop_id", sa.UUID(), nullable=False),
        sa.Column("seats_booked", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "CONFIRMED", "CANCELLED", "EXPIRED", name="booking_status"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dropoff_stop_id"], ["route_stops.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["pickup_stop_id"], ["route_stops.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["rider_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bookings_rider_id"), "bookings", ["rider_id"], unique=False
    )
    op.create_index(op.f("ix_bookings_trip_id"), "bookings", ["trip_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bookings_trip_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_rider_id"), table_name="bookings")
    op.drop_table("bookings")
    # ### end Alembic commands ###
