"""create the RouteStop model

Revision ID: f13120f72de6
Revises: 4aa2d38b0932
Create Date: 2026-09-07 11:38:09.041327

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f13120f72de6"
down_revision: Union[str, Sequence[str], None] = "4aa2d38b0932"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "route_stops",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("eta_offset_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("route_id", "sequence"),
    )
    op.create_index(
        op.f("ix_route_stops_location_id"), "route_stops", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_route_stops_route_id"), "route_stops", ["route_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_route_stops_route_id"), table_name="route_stops")
    op.drop_index(op.f("ix_route_stops_location_id"), table_name="route_stops")
    op.drop_table("route_stops")
    # ### end Alembic commands ###
